apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmn-usr-mngt-dp
  labels:
    app: bmn-usr-mngt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmn-usr-mngt-app
  template:
    metadata:
      labels:
        app: bmn-usr-mngt-app
    spec:
      containers:
        - name: bmn-usr-mngt
          image: mardinpro/bmn-usr-mngt:15
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: bmn-usr-mngt-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bmn-usr-mngt-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bmn-usr-mngt-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 3000
