apiVersion: v1
kind: Service
metadata:
  name: bmn-usr-mngt-service
  namespace: default
spec:
  selector:
    app: bmn-usr-mngt-app
  type: NodePort
  ports:
    - name: bmn-usr-mngt-service
      protocol: TCP
      port: 80
